### PR TITLE
Add UID and GID field access

### PR DESCRIPTION
**Pull request by nichenke**
These changes add in UID and GID property access for ArchiveEntry. The testing is also enhanced to make sure libarchive results match those from python tarfile.

### CODE REVIEW

**Comment by Changaco** [comment]
Looks okay to me, though it would be better if the JSON test files weren't rewritten so much when the actual changes are small, or if the rewrite was fixing the key order so that the problem won't happen again in the future.

**Comment by nichenke** [comment]
Good suggestion on the key order -- I can submit that as well, then rebase this change on top of that.

**Comment by nichenke** [comment]
It doesn't look like either git diff or GitHub diff is sophisticated enough to deal with the JSON differences even after sort_keys=True. Thoughts ?

**Comment by nichenke** [comment]
I'll close these two PRs out and submit fresh - a better way to add UID & GID data without the JSON churn is possible.

**Pull request closed without merging**
