### PR TITLE
fix ArchiveWrite.add_files() chokes on broken symlinks

### PR DESCRIPTION
**Pull request by superr**
Check if file is symlink before opening.

### CODE REVIEW

**Comment by Changaco** [comment]
What do you think, @pombredanne? Should we also skip when `entry.isdev` is true?

**Comment by Changaco** [comment]
@superr Have you confirmed that the change in this PR produces a valid archive? A test would have been nice.

**Comment by superr** [comment]
Yes, it creates a valid archive. I have another small issue but I don't think it is related to this bug.

The command I am using compresses the "ramdisk" directory as well as the files contained in it. I only want to compress the files inside the ramdisk directory and not the ramdisk directory itself. Any suggestions?

**Comment by Changaco** [comment]
@superr Changing the current directory and doing `archive.add_files('.')` is the easiest solution.

**Comment by superr** [comment]
@Changaco This mostly works, but when I mount the archive there is a "." directory which seems to contain unlimited ramdisk directories but does not add size to the archive. If I extract the archive, the "." directory is not there. If I create the gzipped cpio archive using Linux tools, the "." directory does not exist when mounted. 

In case it helps, to accomplish what I need using Linux tools I would do:
```
cd ramdisk
sudo find . | sudo cpio -o -H newc | gzip -9 > ../ramdisk.gz
```

However, I need a cross-platform solution. Any more ideas? Thanks again for your help :)

**Comment by Changaco** [comment]
I'm not sure I understand your problem.

This:

```
os.chdir("ramdisk")
with libarchive.file_writer("../ramdisk.gz", "cpio_newc", "gzip") as archive:
    archive.add_files(".")
```

is pretty much the same thing as the command line you've given.

**Comment by superr** [comment]
the difference is that in my first example I was trying to archive the contents of a directory without specifying any files. The second example I compress a list of files. Seems to be working so far. Thanks again for your help. This pull request does fix the symlink issue I was having :)

**Pull request merged**
