### PR TITLE
Added tox support

### PR DESCRIPTION
**Pull request by krzysztofzuraw**
Added tox support as well as new python version- but to be discussed with @Changaco. There is issue with this [code](https://github.com/Changaco/python-libarchive-c/blob/master/version.py#L31)- it causes tox builds to fail- I can skip building packages in tox.ini but what do you think @Changaco ?

### CODE REVIEW

**Comment by Changaco** [comment]
> There is issue with this [code](https://github.com/Changaco/python-libarchive-c/blob/master/version.py#L31)- it causes tox builds to fail- I can skip building packages in tox.ini but what do you think @Changaco ?

I'm confused, it seems to be working fine on Travis, what exactly is the problem?

**Comment by krzysztofzuraw** [comment]
@Changaco because I already committed the changes via git. In my local instance if I don't have commit files that I made changes I'm not able to install `libarchive-c` via `setup.py`

**Comment by Changaco** [comment]
Ah yes, packaging a dirty working tree is not allowed. I think telling tox to skip the packaging (`usedevelop = True`) is indeed an acceptable solution.

**Comment by krzysztofzuraw** [comment]
@Changaco I made this by `skipsdist=True`

**Comment by Changaco** [comment]
Okay, I'm done. Please review, @krzysztofzuraw.

**Comment by krzysztofzuraw** [comment]
@Changaco :+1: awesome- thanks for your updates :smile:

**Comment by Changaco** [comment]
:-)

**Pull request merged**
