### PR TITLE
Better support of links

### PR DESCRIPTION
**Pull request by Changaco**

### CODE REVIEW

**Comment by Changaco** [comment]
@pombredanne Any idea about the remaining test failure?

**Comment by Changaco** [comment]
The error doesn't occur on my system with a vanilla libarchive 3.1.2.

**Comment by dcolens** [comment]
any plans to merge this ??

**Comment by Changaco** [comment]
I was hoping to find a way to fix the Travis build before merging, but…

**Comment by Changaco** [comment]
Released in version 2.1.

**Comment by dcolens** [comment]
Thanks a lot !!

Did

**Pull request merged**
