### PR TITLE
Run tests verbosely

### PR DESCRIPTION
**Pull request by pombredanne**
... to ensure that the failures output are actually usable

### CODE REVIEW

**Comment by Changaco** [comment]
Why `-s`?

**Comment by Changaco** [comment]
And what information did `-vv` allow you to see that was useful?

**Comment by pombreda** [comment]
@Changaco -s displays any stdout that would have been eventually presented. -vv is essential to see the full diff for failures.
See https://travis-ci.org/Changaco/python-libarchive-c/jobs/61870244 ... what did fail?

**Comment by pombredanne** [comment]
@Changaco do you mind pulling this in? test failure traces are really useless otherwise and I would like to avoid having this commit mixed in other PRs.

**Pull request merged**
